name: Build and Package Plugin

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: composer install --no-dev

      - name: Build plugin package
        run: |
          zip -r plugin.zip .
          mv plugin.zip $GITHUB_WORKSPACE

      - name: Upload plugin package
        uses: actions/upload-artifact@v2
        with:
          name: plugin
          path: plugin.zip
